### ISSUE TITLE
Error: no native implementation of WebCrypto is available in current context

### ISSUE THREAD

**Issue by monicasmith463** [vvo/iron-session#575]
We are facing an issue where the iron-session [v6.3.1] with next [v13.1.2] is throwing the following error from iron-session/edge. Please let us know if you find what's going on. Thank you

```error - Error: no native implementation of WebCrypto is available in current context
    at getCrypto (file:///Users/monicasmith/uf-next/uf-next/node_modules/iron-session/edge/dist/index.mjs:190:9)
    at file:///Users/monicasmith/uf-next/uf-next/node_modules/iron-session/edge/dist/index.mjs:194:15
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)```

**Comment by brc-dd** [comment]
Are you importing the `/edge` module in Node.js (outside middleware.ts)?

**Comment by monicasmith463** [comment]
No, I am not importing /edge in any place other than middleware.ts
