### ISSUE TITLE
Package causing multiple response problem

### ISSUE THREAD

**Issue by lucasantoniooficial** [vvo/iron-session#612]
When testing my application in a production environment, I always get this error in the console:

`Error [ERR_STREAM_WRITE_AFTER_END]: write after end
[front-end] [2023-10-04 06:17:37]     at new NodeError (node:internal/errors:387:5)
[front-end] [2023-10-04 06:17:37]     at ServerResponse.end (node:_http_outgoing:968:15)
[front-end] [2023-10-04 06:17:37]     at ServerResponse.end (/workspace/node_modules/next/dist/compiled/compression/index.js:22:783)
[front-end] [2023-10-04 06:17:37]     at ServerResponse.apiRes.end (/workspace/node_modules/next/dist/server/api-utils/node.js:358:25)
[front-end] [2023-10-04 06:17:37]     at Object.sendError (/workspace/node_modules/next/dist/server/api-utils/index.js:120:9)
[front-end] [2023-10-04 06:17:37]     at Object.apiResolver (/workspace/node_modules/next/dist/server/api-utils/node.js:403:25)
[front-end] [2023-10-04 06:17:37]     at async NextNodeServer.runApi (/workspace/node_modules/next/dist/server/next-server.js:571:9)
[front-end] [2023-10-04 06:17:37]     at async Object.fn (/workspace/node_modules/next/dist/server/next-server.js:1018:35)
[front-end] [2023-10-04 06:17:37]     at async Router.execute (/workspace/node_modules/next/dist/server/router.js:297:32)
[front-end] [2023-10-04 06:17:37]     at async NextNodeServer.runImpl (/workspace/node_modules/next/dist/server/base-server.js:522:29)
[front-end] [2023-10-04 06:17:37] Emitted 'error' event on ServerResponse instance at:
[front-end] [2023-10-04 06:17:37]     at emitErrorNt (node:_http_outgoing:827:9)
[front-end] [2023-10-04 06:17:37]     at processTicksAndRejections (node:internal/process/task_queues:84:21) {
[front-end] [2023-10-04 06:17:37]   code: 'ERR_STREAM_WRITE_AFTER_END'
[front-end] [2023-10-04 06:17:37] }`

Investigating on Google, I came across a problem in another package and it points out that it is the next iron session that causes the problem, with this snippet of code: https://github.com/vvo/iron-session/blob/8280c18ac3ecb7314ecc531bf624e3cbfac211a1/lib/index.js#L72

I would like to know some solution for this.

**Comment by lucasantoniooficial** [comment]
solved, it was just a return in the responses
